# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='uid',
            new_name='pub_id',
        ),
    ]
