# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0002_auto_20180804_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tilt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
