# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0002_auto_20180616_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='muser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsTiltApp.Reaction')),
                ('direction', models.CharField(choices=[('left', 'l'), ('right', 'r')], max_length=1)),
            ],
            bases=('NewsTiltApp.reaction',),
        ),
        migrations.AddField(
            model_name='reaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.Article'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.MUser'),
        ),
    ]
