# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0003_auto_20180712_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsTiltApp.Reaction')),
            ],
            bases=('NewsTiltApp.reaction',),
        ),
    ]
