# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0003_auto_20180804_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='tilt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='muser',
            name='tilt',
            field=models.FloatField(default=0.0),
        ),
    ]
