# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0004_auto_20180806_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tilt',
            field=models.FloatField(default=0.0),
        ),
    ]
