# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0005_auto_20180726_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='NewsTiltApp.Category'),
        ),
    ]
