# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0006_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.Publication'),
        ),
    ]
