# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0007_auto_20180726_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
