# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0008_auto_20180807_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
