# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0008_auto_20180726_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication',
            new_name='source',
        ),
    ]
