# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0009_auto_20180727_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_id',
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
