# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0010_auto_20180727_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muser',
            options={},
        ),
        migrations.RenameField(
            model_name='muser',
            old_name='subscribed_categories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(null=True, to='NewsTiltApp.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsTiltApp.Publication'),
        ),
    ]
