# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0012_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='NewsTiltApp.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='NewsTiltApp.Category'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='categories',
            field=models.ManyToManyField(blank=True, to='NewsTiltApp.Category'),
        ),
    ]
