# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0014_auto_20180802_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
