# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0015_auto_20180802_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
