# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0016_swipe_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='reaction_ptr',
            new_name='action_ptr',
        ),
        migrations.RenameField(
            model_name='swipe',
            old_name='reaction_ptr',
            new_name='action_ptr',
        ),
    ]
