# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsTiltApp.Action')),
            ],
            bases=('NewsTiltApp.action',),
        ),
        migrations.RemoveField(
            model_name='article',
            name='n_views',
        ),
    ]
