# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
