# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0005_publication_tilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='swipe_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='view_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='muser',
            name='conformity_score_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='muser',
            name='conformity_score_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='muser',
            name='like_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='muser',
            name='view_score',
            field=models.FloatField(default=0.0),
        ),
    ]
