# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTiltApp', '0006_auto_20180806_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
