"""Definitions of constants."""

SUCCESS = 0

# Errors
USERNAME_IN_USE = 1
AUTH_FAILED = 4

# Warnings
CATEGORY_ALREADY_SUBSCRIBED = 2
CATEGORY_NOT_SUBSCRIBED = 3

ARTICLES_PER_PULL = 10

MINS_BW_PULLS = 120

HOURS_BW_AUTH_PUB_TILT_RECALC = 24

ARTICLE_SWIPE_WEIGHT = 0.6
ARTICLE_LIKE_WEIGHT = 0.25
ARTICLE_VIEW_WEIGHT = 0.15

USER_BIAS_WEIGHT = 0.1
USER_CONFORMITY_WEIGHT = 0.2
USER_LIKE_WEIGHT = 0.45
USER_VIEW_WEIGHT= 0.25

EPS = 1e-5
